/*
Write multithreaded program that generates the Fibonacci series. The program
should work as follows: The user will enter on the command line the number of
Fibonacci numbers that the program is to generate. The program then will create
a separate thread that will generate the Fibonacci numbers, placing the sequence
in data that is shared by the threads (an array is probably the most convenient
data structure). When the thread finishes execution the parent will output the
sequence generated by the child thread. Because the parent thread cannot begin
outputting the Fibonacci sequence until the child thread finishes, this will require
having the parent thread wait for the child thread to finish.
*/

#include<stdio.h>
#include<stdlib.h>
#include<sys/types.h>
#include<sys/wait.h>
#include<time.h>
#include<unistd.h>
#include<pthread.h>

int n;
int arr[100];
void* fibonacci_thread(void* arg){
    if(n==1){
        arr[0]=0;
        pthread_exit(NULL);
    }
    else if(n==2){
        arr[0]=0;
        arr[1]=1;
        pthread_exit(NULL);
    }
    int i=0;
    int f=0,s=1;
    int copy=n;
    while(copy){
        arr[i]=f;
        int x=s+f;
        f=s;
        s=x;
        copy--;
        i++;
    }
    pthread_exit(NULL);
}

int main(){
    pthread_t t1;
    printf("Enter no of elements");
    scanf("%d",&n);

    pthread_create(&t1,NULL,fibonacci_thread,NULL);
    pthread_join(t1,NULL);
    
    for(int i=0;i<n;i++){
        printf("%d , ",arr[i]);
    }
}